# Generated by Django 3.2 on 2023-05-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230511_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
